services:
  api:
    build: .
    image: secure-api-observability-stack:latest
    container_name: secure-api-observability
    environment:
      - PORT=3000
      # Cambia a 'down' para simular fallo de readiness:
      # - READY_FLAG=down
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/live"]
      interval: 30s
      timeout: 5s
      retries: 3
