services:
  api:
    build: .
    container_name: api-secure-observability
    ports:
    - 3000:3000
    environment:
    - NODE_ENV=production
    - PORT=3000
    depends_on:
    - prometheus
    healthcheck:
      test:
      - CMD
      - wget
      - -qO-
      - http://localhost:3000/ready
      interval: 10s
      timeout: 3s
      retries: 3
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    ports:
    - 9090:9090
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
    - 3001:3000
    volumes:
    - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
    - prometheus
